### ISSUE TITLE
The Load SIARD button has too much importance in the UI

### ISSUE THREAD

**Issue by jmaferreira** [keeps/dbptk-ui#103]
It should be placed under the Manage Databases page (somewhere) and not on the main menu. Eventually, as a submenu of that item (if that's possible).

Also, we are missing a REMOVE database on the UI.

![screen shot 2017-03-19 at 17 03 27](https://cloud.githubusercontent.com/assets/3181302/24082989/959e24f0-0cc6-11e7-86c3-69a6456df3e7.png)
![screen shot 2017-03-19 at 17 03 19](https://cloud.githubusercontent.com/assets/3181302/24082990/959e42c8-0cc6-11e7-864b-38a37ce2056e.png)

**Comment by chalkos** [comment]
If I understood this correctly, you reported 2 issues in here. I created #105 for the "remove database" button.
