### ISSUE TITLE
windows - dbptk gui -> Help->Logs->JVM gives error

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#184]
When user clicks Help->Logs->DBPTK logs then folder with logs opens nicely.
When user clicks Help->Logs->JVM then user gets an error that there are no default application to read this file.
![image](https://user-images.githubusercontent.com/3479156/70696327-218cc080-1ccc-11ea-98e0-2383be576918.png)

Maybe there should be also opened the folder. But as there are a lot of files in that folder then maybe DBPTK should create separate folder for JVM logs and open that...

This is NOT critical issue just a notice

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.7
