### ISSUE TITLE
online deploy issues/suggestions

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#187]
30.12.2019 you deployed dbvtk to online demo environment https://demo.database-preservation.com/

I am trying this out and list here some issues or suggestions:
1. If user logs in our out then user will be directed to the page that is quite blank and where are no links to navigate further
![image](https://user-images.githubusercontent.com/3479156/71580381-1da0d100-2b09-11ea-9aef-01a3d8ef94ba.png)
![image](https://user-images.githubusercontent.com/3479156/71580401-2abdc000-2b09-11ea-9acf-012f59cc200e.png)

2. If regular user (not an adminstrator) makes a search (all records) then the records are nicely presented. But if user clicks on some of these records then user gets "Do not have permission to do this operation
![image](https://user-images.githubusercontent.com/3479156/71580457-69537a80-2b09-11ea-9cda-29c00bc42e86.png)
And the user is directed to outside from "Manage databases" section

3. User gets permission errors on different things but "user" were able to edit metadata of siard. Also if user do not have permissions to do something (for example Load siard file) then maybe user should not have that option in the first place. At the moment user gets the error after selecting the file to upload).

4. When administrator is going through the activity log. For example admin is looking page 101-120 of 299 and clicks on a log entry and clicks "back" then administrator is leaded back to the page 1-20 of 299 so it is very hard to see the information of each row. If the row could be opened as separate tab then it would also be usable.

**Comment by hmiguim** [comment]
Problem 2 is fixed. Mismatch between the resource method name and the permissions properties file.

**Comment by hmiguim** [comment]
Problem 4 is fixed. Every click on the activity log entry opens in a separated tab.

**Comment by 006627** [comment]
Problem 1 is fixed on CAS server configuration

**Comment by Laurira** [comment]
#2 is not actually fixed in https://demo.... . Also I noticed that even the user "administrator" can see these records.

**Comment by hmiguim** [comment]
Close the problem no longer persists
