### ISSUE TITLE
siard import - sybase - error while unmarhsalling JAXB

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#189]
Description: 
I created the SIARD from my 50GB sybase database (latest DBPTK Desktop, windows 10). Seems like the SIARD were created. Now I tried to import it with the same tool
The App do not give me any error. It just keeps thinking:

![image](https://user-images.githubusercontent.com/3479156/72970057-76455000-3dcf-11ea-9d6f-6e8af4933c1d.png)

But there is an error in JVM log.
It also warned me that: "The metadata.xml file did not pass the XML Schema validation."
![image](https://user-images.githubusercontent.com/3479156/72969956-35e5d200-3dcf-11ea-8dd1-42e1658319ef.png)

This is the JVM log
[tmp-9280Hrp16Izh4OYB.txt](https://github.com/keeps/db-visualization-toolkit/files/4102130/tmp-9280Hrp16Izh4OYB.txt)

**Comment by hmiguim** [comment]
Related to https://github.com/keeps/db-preservation-toolkit/issues/428

**Comment by hmiguim** [comment]
Closed at https://github.com/keeps/dbptk-developer/commit/c2fd4e5f34e77dab549ae0876b3538ac4aa5e70a
