### ISSUE TITLE
dbptk enterprise - upload error

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#193]
Clicked Load SIARD (50GB siard file)
it took more than 4 hours and got an error

where are the logs?

**Comment by hmiguim** [comment]
The logs are under the home folder for dbptk-ui, if none is set it should be under /dbvtk/log (https://github.com/keeps/dbptk-enterprise/blob/master/Dockerfile#L20)

**Comment by hmiguim** [comment]
The logs were also improved https://github.com/keeps/dbptk-ui/issues/235 (version 2.5.1)
