### ISSUE TITLE
dbptk enterprise - clicking "Login" (not localhost) goes to "localhost:8080..."

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#194]
Click "Login" to log in
![image](https://user-images.githubusercontent.com/3479156/75322367-416b6380-587b-11ea-83ff-d232082b1b13.png)

Result:
![image](https://user-images.githubusercontent.com/3479156/75322402-521bd980-587b-11ea-9c3b-1a5c79a00524.png)

**Comment by hmiguim** [comment]
CAS configuration is pointing to another address. More information here: https://github.com/keeps/dbptk-ui/blob/master/src/main/resources/config/dbvtk-viewer.properties#L44-L46
