### ISSUE TITLE
Arrays are not yet supported ..

### ISSUE THREAD

**Issue by martenlindstrandx** [keeps/dbptk-ui#198]
We are using version 2.3.1

We got issuses when we tried to archive an oracle instance, we succeded to package the siard file, but we got "Arrays are not yet supported .." when we are trying to validate, visualize or exporting.

Do you have any quickfix to solve this, or do we need to exclude the tables that contain arrays?

log notes:
2020-03-16 13:54:23.365 ERROR 7616 --- [o-auto-1-exec-6] c.d.c.c.common.utils.AsyncCallbackUtils  : [0:0:0:0:0:0:0:1] AsyncCallback error - RESTException: Remote exception caused by GenericException: Arrays are not yet supported. caused by ViewerException: Arrays are not yet supported.

header/metadata.xml:

 <table>
                    <name>AQ$_QUEUES</name>
                    <folder>table3</folder>
                    <columns>
.
.
.
<column>
                            <name>SUBSCRIBERS</name>
                            <type>CHARACTER VARYING(2147483647) ARRAY</type>
                            <typeOriginal>AQ$_SUBSCRIBERS</typeOriginal>
                            <nullable>true</nullable>
                        </column>

**Comment by hmiguim** [comment]
Hi @martenlindstrandx 

At this moment DBPTK Desktop and Enterprise versions doesn't support arrays. If you could, please, export the SIARD but without columns that contains an array data type.

P.S: Sorry for the delayed answer

**Comment by hmiguim** [comment]
Close due to inactivity
