### ISSUE TITLE
manage databases - preparing takes forever, can't delete database either

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#212]
I loaded big 77GB database to DBPTK Desktop. I clicked "Browse" and now it is in "Preparing" state. I can not do anything with it any more. It has been a week in this state. Actually the first and last database both are in "Preparing" state in this screenshot

![image](https://user-images.githubusercontent.com/3479156/81038685-96e17380-8eaf-11ea-8c47-eb1ffd25ae23.png)

If I click "Open" then I get blank page
![image](https://user-images.githubusercontent.com/3479156/81038716-b7113280-8eaf-11ea-9638-463569271dac.png)

There is no option to remove the database as well.

**Comment by hmiguim** [comment]
Close and superseded to https://github.com/keeps/dbptk-ui/issues/242
