### ISSUE TITLE
send to live dbms - loses most of the relations - mysql -> siard2 -> siard2.1 -> postgresql

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#215]
1. Created siard file from mysql and opened it with dbptk desktop (that was 3 years old siard that I had to convert to siard2.1)
![image](https://user-images.githubusercontent.com/3479156/81144269-5e5b9b80-8f7c-11ea-8265-85b318f59eb7.png)

2. This is the metadata of table TOIMIK
![image](https://user-images.githubusercontent.com/3479156/81144952-dffff900-8f7d-11ea-9e40-423b7d4570da.png)

3. This is the metadata of HOONE for example (that has fk to TOIMIK)
![image](https://user-images.githubusercontent.com/3479156/81145081-353c0a80-8f7e-11ea-98be-6200f65cb54e.png)
![image](https://user-images.githubusercontent.com/3479156/81145189-77654c00-8f7e-11ea-84cb-2a0171c45ad0.png)

3. I migrated it into a live database (postgresql). The table "TOIMIK" which had the biggest number of relations do not have any relations any more.
I discovered it when I tried to create a new siard from that database from postgresql.
![image](https://user-images.githubusercontent.com/3479156/81145352-c8754000-8f7e-11ea-9422-4b9a85dc45da.png)

**Comment by Laurira** [comment]
I know that the database is quite bad but dbptk gives no errors after the migration.

**Comment by hmiguim** [comment]
I'll run some tests

**Comment by hmiguim** [comment]
I did the same exercise with the sakila, mysql -> siard-2 -> siard-2.1 -> postgresql -> siard-2.1 and none of the relationships was lost.

**Comment by hmiguim** [comment]
I revisit this issue but I couldn't recreate the original problem. @Laurira can you provide the original SIARD, if not the metadata.xml so I can better analyze the problem?

**Comment by hmiguim** [comment]
Still waiting for feedback, if none provided I'll close this issue and reopen it if new evidences provided.

**Comment by Laurira** [comment]
I tested it and seems like this is not a problem any more. As it is quite old issue then probably some other fix has worked for this issue as well.
