### ISSUE TITLE
Export from SIARD 2.1 to MySQL only exports the first table despite reporting successful completion

### ISSUE THREAD

**Issue by pgoetz** [keeps/dbptk-ui#248]
Description: 
Tested this with versions 2.4.1 and 2.5.3 of the dbptk-desktop appImage and got the same outcome.  Using a MySQL database with 78 tables, I create a SIARD 2.1 file using dbptk-desktop which validates.  I then drop the database and use dbptk-desktop to export the SIARD file back to MySQL.  The screen notifications show 78 tables successfully processed, but when I then go to the database in MySQL it only contains one table; the first table in the database when listed alphabetically.

Operating environment:
    - Ubuntu 14.04 (running as a VirtualBox VM)
   -  MySQL 5.5.62
    - dbptk-desktop-2.5.3.AppImage

Steps required to reproduce the bug:

1. Load fresh database from mysqldump file 
2. Use dbptk-desktop to create a SIARD 2.1 file
    (which validates and reports the correct number of tables)
3. Drop the database
4. Create empty database in MySQL
5. Use dbptk-desktop to export the SIARD file to MySQL

dbptk-desktop finishes, reporting that 78 tables have been processed, but then the resultant MySQL database only contains 

![Screenshot1](https://user-images.githubusercontent.com/1087253/90796139-8f19d380-e2d4-11ea-94a4-ab443f8dc6e9.png)
![Screenshot2](https://user-images.githubusercontent.com/1087253/90796172-950fb480-e2d4-11ea-9057-bc9832f849c7.png)
![Screenshot3](https://user-images.githubusercontent.com/1087253/90796184-980aa500-e2d4-11ea-8cab-68b63dadb8f5.png)
![Screenshot4](https://user-images.githubusercontent.com/1087253/90796198-9e991c80-e2d4-11ea-8f7d-cf04d04c5bc2.png)
![Screenshot5](https://user-images.githubusercontent.com/1087253/90796209-a0fb7680-e2d4-11ea-9abe-abdcc1296e1c.png)
![Screenshot6](https://user-images.githubusercontent.com/1087253/90796223-a48efd80-e2d4-11ea-8c39-02306870a106.png)
![Screenshot7](https://user-images.githubusercontent.com/1087253/90796232-a789ee00-e2d4-11ea-9485-5cffa5148435.png)

Attach any related screenshots below.

**Comment by hmiguim** [comment]
Could you please attach the log file here? They can be found in Help > Logs > DBPTK logs.

**Comment by pgoetz** [comment]
[dbvtk-2020-08-20.0.log.gz](https://github.com/keeps/dbptk-ui/files/5123981/dbvtk-2020-08-20.0.log.gz)

**Comment by pgoetz** [comment]
OK, that's the latest log file. It indicates errors in creating the db tables, but I couldn't find a reason why it was encountering these errors.

**Comment by hmiguim** [comment]
Hi,

could you also send this file $HOME/.dbvtk/reports/report-migration-live-dbms-69227271-d0eb-45c1-b69f-6f9746886887-2020-08-20T14_10_08.222Z.md

**Comment by pgoetz** [comment]
[rlmb-69227271.zip](https://github.com/keeps/dbptk-ui/files/5130049/rlmb-69227271.zip)

**Comment by pgoetz** [comment]
One oddity: In that file I see "Information: target database existed and was used anyway".  The restore wouldn't proceed unless I created the database first: `CREATE DATABASE gco` (I think the error message I got was "database doesn't exist" or something like this.

**Comment by hmiguim** [comment]
Unfortunately our tests were conducted in MySQL version 5.6 and above. You are using 5.5.62 version of MySQL which doesn't support [fractional seconds](https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html) and when DBPTK tries to create the schema it fails because of that. 

> Information: Execution of query ``CREATE TABLE `be_votes` (`id` integer NOT NULL, `contact_id` integer NULL, `bishop_election_id` integer NULL, `consent` bit(1) NULL, `created_at` datetime(6) NULL, `updated_at` datetime(6) NULL, `has_confirmed` bit(1) NULL) ENGINE=INNODB`` failed because of the following error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NULL, `updated_at` datetime(6) NULL, `has_confirmed` bit(1) NULL) ENGINE=INN' at line 1

An option would be upgrade the version of MySQL to at least 5.6 and re-run the migration to a live DBMS

Hope this helps you out

**Comment by pgoetz** [comment]
Thanks.  I'm running all this in an Ubuntu 14.04 VM because the original application this database is associated with was deployed on Ubuntu 14.04. My problem is that I need to demonstrate precise data integrity for archival preservation.  What I've been doing to achieve this so far for mysqldump files is I restore the database from the dump file and then run table checksums `CHECKSUM TABLE airlines;` on each table, comparing the checksums table by table from the original database to the copy. What I've noticed is that if the version of mysql changes, then the table checksums can change, too, as the mysql developers fiddle with some of the data types.  If I change the database engine I honestly have no idea how to go about proving that the SIARD 2.1 file generated from the database has precisely captured all the data.  But in any case, I'll spin up an Ubuntu 16.04 instance and maybe the data types will be constant across those releases.  I very much appreciate your help with this.

**Comment by pgoetz** [comment]
If you can point me to some documentation explaining how people canonically confirm the data integrity of SIARD files, I would be most appreciative.  I haven't been able to find anything.  I looked at the Merkle Tree stuff built in to dbvtk, which looks interesting, but it wasn't clear how I could use this to solve my problem.

**Comment by hmiguim** [comment]
One thing you could do is use our filter module Merkle Tree ([our wiki](https://github.com/keeps/dbptk-developer/wiki/Merkle-Tree-Filter-Module)), it calculates the top-hash of all the database content.

Migrate the data from 5.5.62 to 5.6. Do two SIARD creation process one for each database and apply the merke-tree top hash for both. 

This will produce a JSON file with the top-hash value for the database content. If the two match you have the same data in both systems.

**Comment by pgoetz** [comment]
Thanks, will take a look.  Are you sure that hash doesn't change if the underlying datatype is modified, though? I've tested this (albeit uploading to a MariaDB 10 instance), and got completely different checksums for the same database tables (using the SQL `CHECKSUM TABLE` command.  If the hash is just composed from the UTF8 content, this might actually work.

**Comment by hmiguim** [comment]
The filter module only evaluates the content not the metadata.

**Comment by pgoetz** [comment]
Great!  Thank you; will give it a spin.
