### ISSUE TITLE
dbvtk 2.5.3 can't create SIARD files from a MySQL 5.7.31 database and can't create database from validated SIARD 2.1 file

### ISSUE THREAD

**Issue by pgoetz** [keeps/dbptk-ui#249]
Description: This is related to a previous issue #248, where I couldn't create a database from a SIARD 2.1 file using MySQL 5.5.62 running under Ubuntu 14.04.  I transferred my SIARD file to Ubuntu 16.04 / MySQL 5.7.31 and got timing errors as shown in the attached screenshots. For completeness sake I tried creating a SIARD file from the same database (created from a mysqldump file) and got the same errors.

Browser (Internet explorer, Chrome, Firefox, etc):

Browser version:

Steps required to reproduce the bug:

1. Attempt to load a validated SIARD 2.1 file into MySQL 5.7.31 running on Ubuntu 16.04
![Screenshot_from_2020-08-29_14-22-44](https://user-images.githubusercontent.com/1087253/91645189-b1b09880-ea08-11ea-8b6b-3e13ae7888fd.png)
![Screenshot_from_2020-08-29_14-23-01](https://user-images.githubusercontent.com/1087253/91645196-b9703d00-ea08-11ea-9f91-80fe2049ad59.png)

2. 
3. 

Attach any related screenshots below.

**Comment by hmiguim** [comment]
Select disable encryption and test it again

**Comment by pgoetz** [comment]
Disabling encryption worked; both for creating a SIARD 2.1 file and for turning it back into a MySQL database.  I have not run table checksums yet, but at least all the tables are there, and wow, did it take a long time to repopulate the database from the SIARD file.  Here are some other related issues.  (You will agree that for this stuff to be useful it needs to be fairly robust.)  So I created a SIARD 2.1 file on my Ubuntu 14.04 MySQL 5.5.62, and validated it (see attached validation report).  However when I try to open this SIARD file in dpptk 2.5.3 on my Ubuntu 16.04/MySQL 5.7.31 VM, it won't load (as far as I can tell) -- I just get the bounding blue ball forever.  This is the error message I see in ~/.dbvtk/log/dbvtk.log:

2020-09-01 07:26:57,714 [http-nio-auto-1-exec-2] ERROR c.d.c.c.c.utils.AsyncCallbackUtils - [127.0.0.1] AsyncCallback error - RESTException: Remote exception caused by GenericException: com.databasepreservation.common.exceptions.ViewerException: Error while parsing JSON caused by ViewerException: Error while parsing JSON caused by MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]

If I create a SIARD file from the same database, but loaded in 5.7.31, then it does load, and relatively instantly.  That's the SIARD file I used to recreate the database, btw, since I couldn't get the other one to load.

I tried creating a Merkle tree file and checked the "Explain" box.  The file that was subsequently created is more than 3x as large as the original database dump file (!), and as far as I can tell unreadable by humans:

[pgoetz@frog siard2.1]$ ls -l
total 1242052
-rw-rw-r-- 1 pgoetz pgoetz 985521108 Aug 29 13:36 gco-2015-merkle-tree.json
-rw-rw-r-- 1 pgoetz pgoetz 286324005 Aug 29 13:36 gco-2015_ubuntu1404.siard
drwxr-xr-x 2 pgoetz pgoetz      4096 Sep  1 07:57 validation-reports

Fortunately, it turns out that even though the table checksums are different in MySQL 5.7.31, if I dump the database and re-import it under MySQL 5.5.62, I get the same checksums I had before, so the operation is idempotent.

[dbptk-validation-reporter-gco-2015_ubuntu1404-20200829135942352.txt](https://github.com/keeps/dbptk-ui/files/5157512/dbptk-validation-reporter-gco-2015_ubuntu1404-20200829135942352.txt)

**Comment by hmiguim** [comment]
Regarding the Merkle tree you should only pick the explain tag if you want to debug something. Explain what it does is show every hash used in the Merkle tree top hash calculus process. In this case you only need the top hash value to compare the content of the two migrations.

**Comment by hmiguim** [comment]
I'm going to close this issue, if you have any more questions feel free to open a new issue to discuss it

**Comment by pgoetz** [comment]
I've been busy with another project, so lost track of this, but yes: I most definitely still have an issue, but will open a new ticket for it.
