### ISSUE TITLE
The AppImage file for version 2.5.4 appears to point to version 2.5.2

### ISSUE THREAD

**Issue by pgoetz** [keeps/dbptk-ui#252]
Description: 

On this page: https://github.com/keeps/dbptk-ui/releases/tag/v2.5.4

This is the AppImage link:  https://github.com/keeps/dbptk-desktop/releases/download/v2.5.2/dbptk-desktop-2.5.2.AppImage

**Comment by hmiguim** [comment]
Nice catch! Try again please we fix the links
