### ISSUE TITLE
Human readable SIARD 2.1 file created with 2.5.4 doesn't look like valid XML

### ISSUE THREAD

**Issue by pgoetz** [keeps/dbptk-ui#254]
Description: 
Not sure this is an issue, but I created a human readable SIARD 2.1 file from a MySQL 5.7.31 database, and when I examine the file using a UTF-8 terminal using vim, I see this at the top of the file:

PK^C^D
^@^@^H^@^@Ü
MQ-Ò$è^@^A^@^@^@^A^@^@!^@^T^@content/schema1/table1/table1.xml^A^@^P^@^@^A^@^@^@^@^@^@^@^A^@^@^@^@^@^@<?xml version="1.0" encoding="UTF-8"?>
<table xsi:schemaLocation="http://www.admin.ch/xmlns/siard/2/schema1/table1.xsd table1.xsd" xmlns="http://www.admin.ch/xmlns/siard/2/schema1/table1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
</table>
PK^C^D
^@^@^H^@^@Ü
MQW
×<8a>^R^P^@^@^R^P^@^@!^@^T^@content/schema1/table1/table1.xsd^A^@^P^@^R^P^@^@^@^@^@^@^R^P^@^@^@^@^@^@<?xml version="1.0" encoding="UTF-8" standalone="no"?>

with identical stuff later in the file.  I don't use XSD much, but particularly that dangling </table> looks suspicious.

Browser (Internet explorer, Chrome, Firefox, etc):

Browser version:

Steps required to reproduce the bug:

1. 
2. 
3. 

Attach any related screenshots below.

**Comment by luis100** [comment]
SIARD is a ZIP file with XML files inside. If you'd like to inspect the content, rename the file to end in .zip, extract it and inspect the XML files inside.
