### ISSUE TITLE
Siard files created with SiardFromDb (Swiss Archives) crash DBPTK

### ISSUE THREAD

**Issue by Plucker27** [keeps/dbptk-ui#261]
Description: Siard files (v2.1) created with SiardFromDb (v2.1.120), part of the SIARD Suite (Swiss Federal Archive), cannot be uploaded into the DBPTK (enterprise). The DBPTK application freezes, crashes and has to be reinstalled from scratch. 

Browser (Internet explorer, Chrome, Firefox, etc): Firefox

Browser version: 78.3.1esr (64bits)

Steps required to reproduce the bug:

1. select 'Load SIARD file'
2. drag and drop file
3. 

Attach any related screenshots below.

**Comment by hmiguim** [comment]
Please provide the logs. They are under /dbvtk/log organized by day

**Comment by Plucker27** [comment]
[dbvtk.log](https://github.com/keeps/dbptk-ui/files/5893704/dbvtk.log)
See attached. Yesterdays log is gone because we had to reinstall the application. We tried again today with 2 different siard-files:

- “suite-test1_suite.siard” gives an error but does not cause a crash
- "suite-jik.siard" causes the DBPTK to crash.

**Comment by hmiguim** [comment]
This seems to be the same problem as https://github.com/keeps/dbptk-ui/issues/264

@Plucker27 could you inspect the metadata.xml under header folder and check if there is any column without the mullable tag.

Thanks

**Comment by Plucker27** [comment]
We checked the metadata.xml and _all_ columns are defined without a nullable tag. So, no nullable tags at all in this SIARD.

**Comment by hmiguim** [comment]
There will be a revision cycle and next milestone will bring the fix for this issue. I'll keep this issue open although is the same nature as #264.

**Comment by hmiguim** [comment]
Closed at https://github.com/keeps/dbptk-ui/commit/b3ee9c3c34fa1fa556b6512f658f902e8840d85e
