### ISSUE TITLE
 DBPTK Enterprise user logging/authentication is not usable

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#267]
At the moment DBPTK Enterprise user management is CAS-based and is quite difficult to set up. Also I could not find any free-ware CAS-system.

We suggest that Enterprise should have its own user-registration-login-system (with or without Google or Facebook login) or very detailed instructions how to set it up with freeware CAS so that the Enterprise would be multi-user-system.

Furthermore we should discuss how can DBPTK Enterprise be linked to other systems. For example when an archive has its own search portal then what protocols should DBPTK support so that user will be easily redirected to Enterprise? 
Also should the Enterprise support Google or Facebook login?

**Comment by luis100** [comment]
Apereo CAS is free and open-source: https://github.com/apereo/cas
Apereo CAS 6.0 is now very easy to setup and run: https://github.com/apereo/cas-overlay-template#dockerfile

**Comment by luis100** [comment]
Apereo CAS also supports Google and Facebook login.
Maybe what is then missing is an example deployment that is more easy to reuse.

**Comment by hmiguim** [comment]
Documentation can be consulted at https://github.com/keeps/dbptk-enterprise/tree/master/deploys/development
