### ISSUE TITLE
"Back" button in Search results

### ISSUE THREAD

**Issue by luis100** [keeps/dbptk-ui#269]
Copied from https://github.com/keeps/dbptk-desktop/issues/27

I understand that DBPTK Desktop and Enterprise share the same code for displaying different forms and pages.
Now in Enterprise it is all ok as web browsers have "Back" button.
But in regular DBPTK Desktop if you search and click on different links (moving around according to foreign keys) then you can not go back to previous step. Few releases ago the regular browser shortcut Alt+Left-Arrow worked but at the moment you have to re-start your search process if you need previous results.

I am thinking that separate "Back" button is an idea or at least the "breadcrumb" should be clickable.

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.6
