### ISSUE TITLE
DBPTK-desktop : When I use "Use integrated login", the username and password fields still needs to be filled in.

### ISSUE THREAD

**Issue by Tarjei-stavanger** [keeps/dbptk-ui#272]
Description: 
When I use "Use integrated login", the username and password fields still needs to be filled in.

Browser (Internet explorer, Chrome, Firefox, etc):

DBPTK-desktop

Browser version:

2.5.5

Steps required to reproduce the bug:

1.  Start program
2. Use integrated login
3. Disable encryption

Attach any related screenshots below.

**Comment by Laurira** [comment]
I am not sure DBPTK Desktop has any authentication functionality. Maybe you are talking about "DBPTK Enterprise" which can be accessed with web browser?

**Comment by Tarjei-stavanger** [comment]
The authentication is in the libraries used. They are probably triggered by the connect string.

**Comment by Laurira** [comment]
Ok so you are using "Create Siard" -> Microsoft SQL Server -> Use Integrated login

But you can connect when you type in the credentials?

**Comment by Tarjei-stavanger** [comment]
Yes. I can connect. It is just annoying to type in the credentials and then discover that they are not needed.

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.7
