### ISSUE TITLE
ui browsing - display error with records that are related to missing tables

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#275]
When user clicks on a record then error is displayed:
![image](https://user-images.githubusercontent.com/3479156/115382595-8e2b9f80-a1dd-11eb-91ef-cd801fb8e7b4.png)

I looked into it and understood that it only happens with records that are related to tables that are not existing. For example in my case I try to click on an element in the table "Customer" in database "Sakila". But I did not take table "Store" into that siard snapsot.

But it should not work like that. I understand that issue happens because it tries to create record view of customer and add link to store_id = 1 which is not existing.

It should be fixed so that the record view is nicely displayed but when application adds fk-links it should check if the target table is present and if it is not then it should not add the link (instead it should add "target table missing"-text).

**Comment by Laurira** [comment]
Also this issue can happen when you filter some table during the initial siard creation. For example if you take only half the table.

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.6
