### ISSUE TITLE
ui - edit metadata not always working

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#277]
When changing metadata in already indexed database (I have clicked "browse" before as well) 
![image](https://user-images.githubusercontent.com/3479156/115508001-80c9f000-a285-11eb-9d7a-e979d3795b30.png)

and clicking "Browse" then:
1. Sometimes the changes are not instantly displayed on the first "Information page". If you toggle the "Show technical information" then the changes appear
2. On the search results hovering do not display your additions and when clicking on a table and "Manage table-name" then you can not find your changes either.
![image](https://user-images.githubusercontent.com/3479156/115508603-2ed59a00-a286-11eb-893e-1b7900a50cd4.png)

If you click "Save" via "column-management" then this change will be nicely shown. But I am confused. Does "edit metadata"->"edit-table-column-description" and "column-management"->"edit-column-description" change different things? Because I can nicely see both edits on different forms.

**Comment by hmiguim** [comment]
We have two mechanism to edit metadata that are independent of each other. One to edit metadata that is already indexed without changing the SIARD file (Columns Management under the Configuration menu). And another to edit the metadata in the SIARD file (Edit metadata button under the SIARD card). 

However if you edit the metadata in the SIARD file and it is already indexed the changes do not propagate to the browse part.

**Comment by Laurira** [comment]
I clicked "Delete" under the "Browse" section and clicked again "Browse". So now I should have all changes in the metadata.
![image](https://user-images.githubusercontent.com/3479156/115517924-5893be80-a290-11eb-931d-636df761d204.png)

but the description for last_name is still not there. Actor_id is nicely described.
If I click "SIARD edit metadata" then it still has Description for actor last_name ("perekonnanimi"). So there still exist some bug here.

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.6
