### ISSUE TITLE
ui - database configuration -> table management -> is not showing schemas

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#279]
When user wants to configure the tables under database configuration then the tables seem to be sectioned according to the schemas but its forgotten to show actual names of schemas.

![image](https://user-images.githubusercontent.com/3479156/116199474-d4ce4c00-a73f-11eb-9eab-425f716701c7.png)

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.6
