### ISSUE TITLE
ui - database configuration -> can not hide entire schema

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#280]
Very often users want to hide all tables from some specific schema. At the moment users can not do that. If user goes to configuration -> table management and unselects all tables from some schema then for some reason the application tells you "Please select at least one table to display"

![image](https://user-images.githubusercontent.com/3479156/116200251-c92f5500-a740-11eb-9013-4b000d251e92.png)

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.6
