### ISSUE TITLE
ui -> database configuration -> "The label value must be unique for each schema"

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#281]
1. User goes to the table management 
2. User is doing no changes
3. User clicks "Save"
4. User gets error "The label value must be unique for each schema"
I do not have the same name (or label) in one schema. However I have the same name and label in two different schemas.

![image](https://user-images.githubusercontent.com/3479156/116201449-2d9ee400-a742-11eb-8c97-6ed0cfeea836.png)

I can send metadata.xml to developer by e-mail if needed

**Comment by Laurira** [comment]
If I added string "1" to each label in my second schema then I did not get the error. So there should be fixed the error message and explained why I can't have the same label in two different schemas or this check has to be removed.

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.6
