### ISSUE TITLE
ui save search - cancel button works unexpectedly

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#284]
This is very low priority issue.

1. In the beginning of this test I have zero "Saved searches"
![image](https://user-images.githubusercontent.com/3479156/116980546-08c0e880-accf-11eb-9aeb-fd603dc7da1d.png)
2. Now I click on table Sakila -> actor, then I click "advanced" and then I click "SAVE SEARCH". Next from is displayed:
![image](https://user-images.githubusercontent.com/3479156/116980754-4c1b5700-accf-11eb-80b9-8bf1ab18ec2f.png)
3. Now when I click "CANCEL" then I will be redirected on my searches and this search is still saved:
![image](https://user-images.githubusercontent.com/3479156/116980835-681ef880-accf-11eb-98cb-e656c2831444.png)

I think the proper behavior would be that user will be directed to previous display (table actor) and no search is saved. Currently search is saved at the moment when user clicked "SAVE SEARCH" no matter what user will click next.

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.6
