### ISSUE TITLE
Options to format numeric columns presentation

### ISSUE THREAD

**Issue by luis100** [keeps/dbptk-ui#288]
![117466329-7dec2200-af4a-11eb-90e7-eb94fd35965c](https://user-images.githubusercontent.com/1252710/119788653-3b26c580-beca-11eb-9bf3-5ec0c061ad4d.png)

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.6
