### ISSUE TITLE
dbptk enterprise - keeps thinking when clicking on a database

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#297]
I restarted dbptk enterprise.

I opened the browser and saw the list of previously loaded databases.

When I click on of these then nothing happens.

In the log there are no errors.
![image](https://user-images.githubusercontent.com/3479156/127898414-39cbe7d0-f369-4eea-8ee3-0a2c873af548.png)

If I load new database then it works.

Is it normal behavior? Is there anything I can do to see already loaded databases or should I always re-load databases when I restart the DBPTK?

**Comment by Laurira** [comment]
Also when I use "regular" (non-administrator) user then after login I get this message:
![image](https://user-images.githubusercontent.com/3479156/127977722-eec93f5e-2fb1-4324-8849-c2bdfa07304d.png)

but after clicking "Close" it shows databases
![image](https://user-images.githubusercontent.com/3479156/127977797-3b1d2306-e8e5-4ea2-92d1-824f8493c93c.png)

**Comment by hmiguim** [comment]
I need a bit more of context if possible. Did you run it via docker-compose?

**Comment by Laurira** [comment]
Yes. I am thinking that https://github.com/keeps/dbptk-ui/issues/301 answers that question, so I will close it.
