### ISSUE TITLE
DBPTK Desktop - error while creating SIARD

### ISSUE THREAD

**Issue by mindw0rks** [keeps/dbptk-ui#314]
I'm getting message - non supported character set (add orai18n.jar in your classpath) BLT8MSWIN1257.

![error](https://user-images.githubusercontent.com/92082701/159429851-addcf0b5-37a6-47a6-8ebe-7c678251cc59.PNG)

**Comment by luis100** [comment]
Currently, we have no option to add extra jars to DBPTK Desktop Oracle module. You'll need to use DBPTK developer to export your Oracle database to SIARD and add the additional jar in the same way you'd add an additional JDBC driver:

https://github.com/keeps/dbptk-developer/wiki/How-to-use-a-JDBC-driver-in-DBPTK-Developer#unix-system
