### ISSUE TITLE
Indexing stuck in Preparing state

### ISSUE THREAD

**Issue by finnove** [keeps/dbptk-ui#357]
# Description
When an unsupported SIARD is loaded, the indexing can stop at a specific table. 
The status will be stuck in "Preparing". 
Problem: Its not possible to delete this database entry easily, and multiple efforts can make it worse.

# Previous workaround tried: 
- Used swagger-ui to find a curl command to delete the collection. Then the status will change, and I can delete the database in the GUI as before.
- Removing tables that are problematic, with a siard-to-siard conversion (but the old efforts are still visible in the catalog)

# Context
DBPTK Enterprise

# Suggested solution
* Please make it possible to delete a database that is stuck in the "Preparing" state from the GUI
* swagger-ui is turned off in recent versions. how to enable, or find the proper curl commands / api documentation?
- or remind us of the proper curl command for this situation

**Comment by hmiguim** [comment]
It was agreed to on every DBPTK initialization looking for databases that were in INGESTING state and marked as ERROR so it can be deleted via WUI

**Comment by hmiguim** [comment]
release on version [2.8.0](https://github.com/keeps/dbptk-ui/releases/tag/v2.8.0)
