### ISSUE TITLE
Advanced search is hidden away

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/dbptk-ui#54]
Reported by a colleage at the DNA:

Advanced search is hidden away in the "arrow down" sign.
![advancedsearchfield](https://cloud.githubusercontent.com/assets/15984159/17773234/ad02e8ae-654d-11e6-86fe-a7f914968cee.PNG)

**Comment by chalkos** [comment]
I kind of agree with this. A small `Advanced` button where the arrow is might be the way to go.

**Comment by hmiguim** [comment]
Fixed
