### ISSUE TITLE
"Show less" function = 100 records

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/dbptk-ui#55]
Reported by a colleage at the DNA:

The default amount of records shown in tables are 20.
The show more function works fine.
When you want to "show less" the minimum amount is 100.
Should it be 20?

**Comment by chalkos** [comment]
Yes. This is an odd behaviour from the component being used.

@luis100 do you also have this problem in RODA?

**Comment by hmiguim** [comment]
Fix release on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.7
