### ISSUE TITLE
Use sticky-kit for sidebar to acompanny scroll

### ISSUE THREAD

**Issue by chalkos** [keeps/dbptk-ui#74]
_From @luis100 on November 9, 2016 11:50_

http://leafo.net/sticky-kit/

Check how RODA does this for GWT.

_Copied from original issue: keeps/db-preservation-toolkit#280_

**Comment by hmiguim** [comment]
Using position: sticky (https://developer.mozilla.org/en-US/docs/Web/CSS/position)
